name: "Release Firefox"
on:
  push:
    branch:
    - master

  workflow_dispatch:

jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .
          filename: "{name}-{version}.xpi"
          ignoreFiles: '["trigger_lists/", "README.md", "index.html", "assets/js/index.js"]'

      - name: Upload a Unsigned XPI
        uses: actions/upload-artifact@v3.1.0
        with:
          name: triggerremover.unsigned.xpi
          path: ${{ steps.web-ext-build.outputs.target }}
